/**
 * Auto-generated TypeScript types from OpenAPI contract.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Regenerate with: npx openapi-typescript ../docs/seams/catalog-management/contracts/openapi.yaml -o src/types/api.ts
 *
 * Contract source: docs/seams/catalog-management/contracts/openapi.yaml
 */

export interface components {
  schemas: {
    /** Brand response */
    BrandResponse: {
      /** Brand ID */
      id: number;
      /** Brand name */
      brand: string;
    };

    /** Type response */
    TypeResponse: {
      /** Type ID */
      id: number;
      /** Type name */
      type: string;
    };

    /** Catalog item response with full details */
    CatalogItemResponse: {
      /** Catalog item ID */
      id: number;
      /** Product name */
      name: string;
      /** Product description */
      description?: string | null;
      /** Product price */
      price: string; // Decimal serialized as string
      /** Image filename */
      picture_file_name: string;
      /** Full image URI (/Pics/{filename}) */
      picture_uri: string;
      /** Brand foreign key */
      catalog_brand_id: number;
      /** Type foreign key */
      catalog_type_id: number;
      /** Brand details */
      brand: components["schemas"]["BrandResponse"];
      /** Type details */
      type: components["schemas"]["TypeResponse"];
      /** Current stock level */
      available_stock: number;
      /** Restock alert threshold */
      restock_threshold: number;
      /** Maximum stock capacity */
      max_stock_threshold: number;
    };

    /** Pagination metadata */
    PaginationMetadata: {
      /** Current page (zero-based) */
      page: number;
      /** Items per page */
      limit: number;
      /** Total items across all pages */
      total_items: number;
      /** Total pages */
      total_pages: number;
    };

    /** Paginated list of catalog items */
    CatalogItemListResponse: {
      /** Catalog items */
      items: Array<components["schemas"]["CatalogItemResponse"]>;
      /** Pagination details */
      pagination: components["schemas"]["PaginationMetadata"];
    };

    /** Request body for creating a catalog item */
    CatalogItemCreate: {
      /** Product name (required, 1-50 chars) */
      name: string;
      /** Product description (optional) */
      description?: string | null;
      /** Product price (required, 0-999999999.99, max 2 decimals) */
      price: string; // Decimal as string
      /** Brand foreign key (required) */
      catalog_brand_id: number;
      /** Type foreign key (required) */
      catalog_type_id: number;
      /** Initial stock level (required, 0-10000000) */
      available_stock: number;
      /** Restock alert threshold (required, 0-10000000) */
      restock_threshold: number;
      /** Maximum stock capacity (required, 0-10000000) */
      max_stock_threshold: number;
      /** Temporary image filename from upload (optional) */
      temp_image_name?: string | null;
    };

    /** Request body for updating a catalog item */
    CatalogItemUpdate: {
      /** Product name (required, 1-50 chars) */
      name: string;
      /** Product description (optional) */
      description?: string | null;
      /** Product price (required, 0-999999999.99, max 2 decimals) */
      price: string; // Decimal as string
      /** Brand foreign key (required) */
      catalog_brand_id: number;
      /** Type foreign key (required) */
      catalog_type_id: number;
      /** Stock level (required, 0-10000000) */
      available_stock: number;
      /** Restock threshold (required, 0-10000000) */
      restock_threshold: number;
      /** Maximum stock (required, 0-10000000) */
      max_stock_threshold: number;
      /** New image filename (optional, preserves existing if null) */
      temp_image_name?: string | null;
    };

    /** Response after temporary image upload */
    TempImageResponse: {
      /** Temporary filename (UUID + extension) */
      temp_filename: string;
    };

    /** Error detail structure */
    ErrorDetail: {
      /** Machine-readable error code */
      code: string;
      /** Human-readable error message */
      message: string;
      /** Additional error context */
      details?: Record<string, unknown> | null;
      /** Correlation ID for error tracking */
      request_id?: string | null;
    };

    /** Standard error response envelope */
    ErrorResponse: {
      /** Error details */
      error: components["schemas"]["ErrorDetail"];
    };
  };
}

export interface paths {
  "/catalog/items": {
    /** List catalog items with pagination */
    get: {
      parameters: {
        query?: {
          /** Page number (zero-based) */
          page?: number;
          /** Items per page */
          limit?: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["CatalogItemListResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };

    /** Create catalog item */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CatalogItemCreate"];
        };
      };
      responses: {
        201: {
          content: {
            "application/json": components["schemas"]["CatalogItemResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };

  "/catalog/items/{item_id}": {
    /** Get catalog item details */
    get: {
      parameters: {
        path: {
          /** Catalog item ID */
          item_id: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["CatalogItemResponse"];
          };
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };

    /** Update catalog item */
    put: {
      parameters: {
        path: {
          /** Catalog item ID */
          item_id: number;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CatalogItemUpdate"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["CatalogItemResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };

    /** Delete catalog item */
    delete: {
      parameters: {
        path: {
          /** Catalog item ID */
          item_id: number;
        };
      };
      responses: {
        204: {
          description: "Item deleted successfully";
        };
        404: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };

  "/catalog/brands": {
    /** List all catalog brands */
    get: {
      responses: {
        200: {
          content: {
            "application/json": Array<components["schemas"]["BrandResponse"]>;
          };
        };
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };

  "/catalog/types": {
    /** List all catalog types */
    get: {
      responses: {
        200: {
          content: {
            "application/json": Array<components["schemas"]["TypeResponse"]>;
          };
        };
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };

  "/images/upload": {
    /** Upload temporary product image */
    post: {
      requestBody: {
        content: {
          "multipart/form-data": {
            /** Image file to upload */
            file: Blob;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["TempImageResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        500: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
}

// Type aliases for convenience
export type BrandResponse = components["schemas"]["BrandResponse"];
export type TypeResponse = components["schemas"]["TypeResponse"];
export type CatalogItemResponse = components["schemas"]["CatalogItemResponse"];
export type CatalogItemListResponse = components["schemas"]["CatalogItemListResponse"];
export type PaginationMetadata = components["schemas"]["PaginationMetadata"];
export type CatalogItemCreate = components["schemas"]["CatalogItemCreate"];
export type CatalogItemUpdate = components["schemas"]["CatalogItemUpdate"];
export type TempImageResponse = components["schemas"]["TempImageResponse"];
export type ErrorResponse = components["schemas"]["ErrorResponse"];
export type ErrorDetail = components["schemas"]["ErrorDetail"];
